# Basic setups
env: MultiGoal-v0
algo: meow
seed: 0
description: base
deterministic: true

# Training parameters 1
buffer_size: 1000000
eval_every: 800
plot_every: 800
steps: 6000
warmup_steps: 1000
test_num: 10
device: cuda

# Training parameters 2
batch_size: 256
lr: 0.001
grad_clip: 30
weight_decay: 0

# Network parameters
gamma: 0.9
tau: 0.0005
alpha: 2.5
sigma_max: 1.0
sigma_min: -2.0

# Flow parameters
init_parameters_context_encoder: "zero"
init_parameters_flow: "orthogonal"
init_parameters_reward_shift: "zero"

dropout_rate_flow: 0.1
dropout_rate_reward_shift: 0.0

layernorm_context_encoder: true
layernorm_flow: true
layernorm_reward_shift: true

n_flow_layers: 2
n_hidden_layers_context_encoder: 2
n_hidden_layers_flow: 2
n_hidden_layers_reward_shift: 2

n_hidden_units_context_encoder: 64
n_hidden_units_flow: 64
n_hidden_units_reward_shift: 256